<a href="https://colab.research.google.com/github/andymeta/ColabRepo/blob/main/MyFirstColab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my= range(2,8)
type(my)

range

In [ ]:
s = "imag-%d.jpg" %(1)
s

'imag-1.jpg'

In [ ]:
!/opt/bin/nvidia-smi

Tue May  3 07:46:53 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# New content


# 新段落

In [ ]:
type(1.0)

float

In [ ]:
i=5
while i>1:
  print("%d" %i)
  i -=1

5
4
3
2


In [ ]:
mydics={"first":'3',"sencond":8,"fifth":99}
mydics.popitem()
for k,v in mydics.items():
  print("k=%s, v=%s" %(k,type(v)))

k=first, v=<class 'str'>
k=sencond, v=<class 'int'>


In [ ]:
for k in mydics.keys():
  print("%s" %k)
type(k)

first
sencond
fifth


str

In [ ]:
for i in ['first','ss',5]:
  print("%s" %(type(i)))

<class 'str'>
<class 'str'>
<class 'int'>


In [ ]:
while True:
  inputc=input("please input some characters:")
  if inputc=='stop':
    break


please input some characters:skjf
please input some characters:ajfadf 
please input some characters:stop


In [ ]:
def func1(str):
  """
  my first function definition.
  """
  str = 'x'
  print(str)
func1.__name__
s = 'sky'
func1(s)
s

x


'sky'

In [ ]:
func1.__file__

AttributeError: ignored

In [ ]:
str = 'asff'
print(id(str))
str='sfdfdf'
print(id(str))
list1=[1,2,'22']
print(id(list1))
list1=[2,3,'44',3]
print(id(list1))

139769128643568
139769100899056
139769068888704
139769068787104


In [4]:
def judgeType(inputParam):
  if isinstance(inputParam,int):
    print("type is %s" %('int'))
  elif isinstance(inputParam,list):
    print('type is list')

judgeType(33)
judgeType([3,55,'22'])

  

  

type is int
type is list


In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [1]:
class Fridge:
  clsfoods={}
  def __init__(self, items={}):
    if not isinstance(items,dict):
      raise TypeError("Fridge need a dictionary for initialization")
    self.fooditems = items
    return
  
  def add_multi(self, foodname, quantity):
    if(foodname not in self.fooditems):
      self.fooditems[foodname] = 0
    if(foodname not in Fridge.clsfoods.items()):
      Fridge.clsfoods[foodname] =0
    self.fooditems[foodname] += quantity
    Fridge.clsfoods[foodname] += quantity

foods={'apple':2, 'orange':5, 'banana':88}
f=Fridge(foods)
#f.items['orange'] = 2
f.add_multi('strawberry',10)
f.add_multi('watermelon',11)
print('orange number is %d' %(foods['orange']))
for item in f.fooditems:
  print(item)
print('..............f2.........')
f2 = Fridge({})
print('f2 len = %d' %(len(f2.clsfoods)))
for item in f2.clsfoods.items():
  print(item)

# base class of any food
#
class CanBeEaten():
  name=''
  def __init__(self,name) -> None:
    CanBeEaten.name = name    

#class of food
class Food(CanBeEaten):
  def __init__(self, name,weight=0, ingredients={}) -> None:
      super().__init__(name)
      self.weight = weight
      self.__ingredients = ingredients
  #
  def getName(self):
    return self.name
  def addNewIngredient(self, ing):
    if(isinstance(ing,dict)):
      self.__ingredients.update(ing)
  def getIngredCount(self):
    return len(self.__ingredients)

  def getIngredValue(self,k):
    if k in self.__ingredients.keys():
      return self.__ingredients[k]
    
  def changeIngredientCount(self,key, newvalue):
    if(key in self.__ingredients.keys()):
      self.__ingredients[key]=newvalue

# mian program
#
salad = Food('SALAD', 19)
salad.addNewIngredient({'apple':0.1, 'carrot':0.1})
n = salad.getIngredCount()

print('there are %d ingredients of %s' %(n, salad.getName()))
salad.changeIngredientCount('apple',0.3)
print('%s value is %f' %('apple', salad.getIngredValue('apple')))


orange number is 5
apple
orange
banana
strawberry
watermelon
..............f2.........
f2 len = 2
('strawberry', 10)
('watermelon', 11)
there are 2 ingredients of SALAD
apple value is 0.300000


In [3]:
import sys
print(sys.path)
print('%s' %sys.argv)

['', '/content', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '/root/.ipython']
['/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py', '-f', '/root/.local/share/jupyter/runtime/kernel-ad666998-7c9e-4de6-b58f-50d3caf95260.json']


In [4]:
import os.path as op
import sys
def split_fullpath(path):
  parentpath, name = op.split(path)
  if name=='':
    return (parentpath,)
  else:
    return split_fullpath(parentpath) + (name,)

path = sys.argv[0]
print('path = %s' %path)

res = split_fullpath(path)
print('result = %s' % str(res))


path = /usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py
result = ('/', 'usr', 'local', 'lib', 'python3.7', 'dist-packages', 'ipykernel_launcher.py')


In [5]:
r= range(10,20)
type(r)

range

In [6]:
type(*r)

TypeError: ignored

In [7]:
print(*r)

10 11 12 13 14 15 16 17 18 19


In [8]:
r[0]

10

In [ ]:
import os
os.execl('/bin/cat','cat','/etc/motd')

In [2]:
import sys
dir()

['__breakpointhook__',
 '__displayhook__',
 '__doc__',
 '__excepthook__',
 '__interactivehook__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__stderr__',
 '__stdin__',
 '__stdout__',
 '_clear_type_cache',
 '_current_frames',
 '_debugmallocstats',
 '_framework',
 '_getframe',
 '_git',
 '_home',
 '_xoptions',
 'abiflags',
 'api_version',
 'argv',
 'base_exec_prefix',
 'base_prefix',
 'breakpointhook',
 'builtin_module_names',
 'byteorder',
 'call_tracing',
 'callstats',
 'copyright',
 'displayhook',
 'dont_write_bytecode',
 'exc_info',
 'excepthook',
 'exec_prefix',
 'executable',
 'exit',
 'flags',
 'float_info',
 'float_repr_style',
 'get_asyncgen_hooks',
 'get_coroutine_origin_tracking_depth',
 'get_coroutine_wrapper',
 'getallocatedblocks',
 'getcheckinterval',
 'getdefaultencoding',
 'getdlopenflags',
 'getfilesystemencodeerrors',
 'getfilesystemencoding',
 'getprofile',
 'getrecursionlimit',
 'getrefcount',
 'getsizeof',
 'getswitchinterval',
 'gettrace',
 'hash_inf

In [3]:
import os
os.getcwd()

'/content'

In [4]:
os.listdir(os.getcwd())

['.config', 'sample_data']

In [5]:
for item in os.listdir(os.getcwd()):
  print(item)

.config
sample_data


In [6]:
import os
for item in os.listdir(os.getcwd()):
  print('%s'% os.path.join(os.getcwd(),item))

#os.stat(os.getcwd())

/content/.config
/content/sample_data


In [1]:
!pip show matplotlib

Name: matplotlib
Version: 3.2.2
Summary: Python plotting package
Home-page: https://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: matplotlib-users@python.org
License: PSF
Location: /usr/local/lib/python3.7/dist-packages
Requires: python-dateutil, kiwisolver, cycler, numpy, pyparsing
Required-by: yellowbrick, seaborn, scikit-image, pycocotools, plotnine, pandas-profiling, mlxtend, mizani, missingno, matplotlib-venn, keras-vis, imgaug, fbprophet, fastai, descartes, daft, arviz


In [2]:
!pip show numpy

Name: numpy
Version: 1.21.6
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
Required-by: yellowbrick, xgboost, xarray, wordcloud, torchvision, torchtext, tifffile, thinc, Theano-PyMC, tensorflow, tensorflow-probability, tensorflow-hub, tensorflow-datasets, tensorboard, tables, statsmodels, spacy, sklearn-pandas, seaborn, scs, scipy, scikit-learn, scikit-image, resampy, qdldl, PyWavelets, python-louvain, pystan, pysndfile, pymc3, pyerfa, pyemd, pycocotools, pyarrow, plotnine, patsy, pandas, osqp, opt-einsum, opencv-python, opencv-contrib-python, numexpr, numba, nibabel, netCDF4, moviepy, mlxtend, mizani, missingno, matplotlib, matplotlib-venn, lightgbm, librosa, Keras-Preprocessing, kapre, jpeg4py, jaxlib, jax, imgaug, imbalanced-learn, imageio, hyperopt, holoviews, h5py, gym, gensim, folium, fix-yahoo-f

In [3]:
!which python


/usr/local/bin/python


In [4]:
!python

Python 3.7.13 (default, Apr 24 2022, 01:04:09) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()


In [5]:
!pip show scipy

Name: scipy
Version: 1.4.1
Summary: SciPy: Scientific Library for Python
Home-page: https://www.scipy.org
Author: None
Author-email: None
License: BSD
Location: /usr/local/lib/python3.7/dist-packages
Requires: numpy
Required-by: yellowbrick, xgboost, Theano-PyMC, statsmodels, sklearn-pandas, seaborn, scs, scikit-learn, scikit-image, resampy, qdldl, pymc3, plotnine, osqp, mlxtend, missingno, matplotlib-venn, lightgbm, librosa, jaxlib, jax, imgaug, imbalanced-learn, hyperopt, gym, gensim, fastai, fa2, ecos, cvxpy, arviz, albumentations


In [2]:
arr.flat[7]

7

In [4]:
a = arr.ravel().reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [5]:
a.ndim

3

In [6]:
a.size

24

In [7]:
a.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [8]:
np.dsplit(a,4)

[array([[[ 0],
         [ 4],
         [ 8]],
 
        [[12],
         [16],
         [20]]]), array([[[ 1],
         [ 5],
         [ 9]],
 
        [[13],
         [17],
         [21]]]), array([[[ 2],
         [ 6],
         [10]],
 
        [[14],
         [18],
         [22]]]), array([[[ 3],
         [ 7],
         [11]],
 
        [[15],
         [19],
         [23]]])]

In [9]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
ls = arr.tolist()
type(ls)

list

In [12]:
ls[0]

[0, 1, 2, 3, 4, 5]

In [13]:
ls[0][1]

1

In [16]:
arr2 = np.array(ls)
arr2.shape

(4, 6)

In [3]:
import numpy as np
np.savetxt('mytxt.txt',arr)

NameError: ignored

In [19]:
!ls
!scp

mytxt.txt  sample_data
usage: scp [-346BCpqrv] [-c cipher] [-F ssh_config] [-i identity_file]
           [-l limit] [-o ssh_option] [-P port] [-S program]
           [[user@]host1:]file1 ... [[user@]host2:]file2


In [1]:
!ls

sample_data


In [8]:
import numpy as np
arr = np.arange(24).reshape(4,6)
np.savetxt('mytxt.txt',arr,fmt='%.2f')
#
C,V=np.loadtxt('sample_data/data.csv',delimiter=',',usecols=(6,7),unpack=True)
arr2=np.zeros((C.shape[0],2))
CV=np.vstack((C,V))
#
CT=np.array([C])
VT=np.array([V])
CV2=np.hstack((CT.T,VT.T))


In [10]:
CV.T[0].shape

(2,)